name: smartwatch_client_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  pointycastle: ^3.9.1
  crypto: ^3.0.7
  flutter_secure_storage: ^9.2.2
  flutter_blue_plus: ^2.0.0
  http: ^1.2.0
  permission_handler: ^11.3.1
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true